export const dummyData = [
  {
    id: "01JAC8CXW0MHC3K9AN75T2DZK2",
    name: "Nowell Jeanon",
    university: "Ecole Nationale d'Architecture",
    job: "Account Executive",
  },
  {
    id: "01JAC8CXW2CFYBSTZ06795RFNJ",
    name: "Tildi Dand",
    university: "London School of Business & Finance",
    job: "Budget/Accounting Analyst IV",
  },
  {
    id: "01JAC8CXWBHSH3CQFYR7VHCCK3",
    name: "Benedicta Smorthit",
    university: "Russian Academy of Theatre Arts",
    job: "Geological Engineer",
  },
  {
    id: "01JAC8CXWC26VFTPQCGVJED2W7",
    name: "Evonne Rogeon",
    university: "University of Montenegro",
    job: "Financial Advisor",
  },
  {
    id: "01JAC8CXWDHGJG24JCHQXECVDK",
    name: "Corly Meriel",
    university: "Institute of Teachers Education, Kent",
    job: "Sales Associate",
  },
  {
    id: "01JAC8CXWECN6DBM5VFD2A1CQJ",
    name: "Isador Humbie",
    university: "Elmira College",
    job: "Professor",
  },
  {
    id: "01JAC8CXWFCS0DF0A1Q3JJDE0Y",
    name: "Mathias Parley",
    university: "Poznan School of Banking",
    job: "Recruiter",
  },
  {
    id: "01JAC8CXWGX8Q6XW91TM476TGA",
    name: "Gregor Colbourn",
    university: "Dubna International University for Nature, Society and Man",
    job: "Software Test Engineer IV",
  },
  {
    id: "01JAC8CXWHE2MS9CQGGQJSC5M8",
    name: "Ainslie Skene",
    university: "Université Libre de Bruxelles",
    job: "VP Accounting",
  },
  {
    id: "01JAC8CXWJHFAG8WTH7F1PBZ1Z",
    name: "Selby Gorini",
    university: "Chukyo Women's University",
    job: "Community Outreach Specialist",
  },
  {
    id: "01JAC8CXWJV1NE9Y4SHGWDFND2",
    name: "Laney Stallwood",
    university: "Universidad Interamericana de Puerto Rico",
    job: "VP Sales",
  },
  {
    id: "01JAC8CXWKWD70PTK6VNVWFGPC",
    name: "Jackie Lathom",
    university: "Seisen University",
    job: "Senior Cost Accountant",
  },
  {
    id: "01JAC8CXWMSS695RW36H6PD4FZ",
    name: "Tadio Woolhouse",
    university: "Johore Bharu Primeir Polytechnic",
    job: "Pharmacist",
  },
  {
    id: "01JAC8CXWMNDY97GZ19A0RSNZ0",
    name: "Amalee Piggens",
    university: "Universidad Politécnica de Madrid",
    job: "Librarian",
  },
  {
    id: "01JAC8CXWNHZZ6M4M8FWGGSHTS",
    name: "Helyn Pindred",
    university: "Centre College",
    job: "Accountant IV",
  },
  {
    id: "01JAC8CXWPFWM7XFH0WTV3WQE8",
    name: "Byram Swindlehurst",
    university: "Notre Dame Women's College",
    job: "Structural Engineer",
  },
  {
    id: "01JAC8CXWQ8682JT8E961CHMT5",
    name: "Cynthy Fattore",
    university: "University of Craiova",
    job: "Legal Assistant",
  },
  {
    id: "01JAC8CXWQRY2K837KKMTABGE2",
    name: "Eadith Biddulph",
    university: "Ecole Superieure des Télécommunications",
    job: "Safety Technician I",
  },
  {
    id: "01JAC8CXWRJN02SPJY9G3ZTX59",
    name: "Wallis Flew",
    university: "Al-Manar University",
    job: "Senior Quality Engineer",
  },
  {
    id: "01JAC8CXWSBSBEW61AYXQN6HHE",
    name: "Ceil Eves",
    university: "Universitas Pesantren Darul Ulum Jombang",
    job: "Librarian",
  },
  {
    id: "01JAC8CXWTEMMPHWG2KWBE2FWT",
    name: "Kurt Colvill",
    university: "National University of Ireland, Maynooth",
    job: "Marketing Assistant",
  },
  {
    id: "01JAC8CXWVQQX4DP2TYYHW00SG",
    name: "Gaston Sands-Allan",
    university: "Bezalel Academy of Art and Design",
    job: "Research Associate",
  },
  {
    id: "01JAC8CXXD1J904CJDQ3THB05D",
    name: "Alphonse Girkin",
    university: "School of Pharmacy, University of London",
    job: "Geological Engineer",
  },
  {
    id: "01JAC8CXXE44H3NMVME05E7D9A",
    name: "Jasun Walak",
    university: "Hodeidah University",
    job: "Nurse Practicioner",
  },
  {
    id: "01JAC8CXXF958PJ1H8J3VE7XZ6",
    name: "Maurits Parcells",
    university: "Russell Berrie Nanotechnology Institute",
    job: "Assistant Media Planner",
  },
  {
    id: "01JAC8CXXGXRTQPR9J1163QSQG",
    name: "Berni Norheny",
    university: "University of Montana Western",
    job: "Web Developer I",
  },
  {
    id: "01JAC8CXXHSR397Y6AQHVHDCD0",
    name: "Townie Stennet",
    university: "Musashino Art University",
    job: "Recruiter",
  },
  {
    id: "01JAC8CXXHZP51WPK058MCY6MC",
    name: "Petronille Clementson",
    university: "Bashkir State Medical University",
    job: "Operator",
  },
  {
    id: "01JAC8CXXJK1NDP31GZK579FQY",
    name: "Tonya Batrip",
    university: "Mizan Tepi University",
    job: "Executive Secretary",
  },
  {
    id: "01JAC8CXXKB03B3AGRSXKXVP07",
    name: "Prentice Derricoat",
    university: "Deutsche Sporthochschule Köln",
    job: "Mechanical Systems Engineer",
  },
  {
    id: "01JAC8CXXMHAC05G3669BGCHX4",
    name: "Tadeo Mann",
    university: "Takachiho University",
    job: "Electrical Engineer",
  },
  {
    id: "01JAC8CXXN1KWKZJK4M595NCX9",
    name: "Alan Wiggins",
    university: "Nara University of Commerce",
    job: "Marketing Assistant",
  },
  {
    id: "01JAC8CXXPXSMWF5TF10CN7567",
    name: "Ignacius Druce",
    university: "Universidad Pedagógica Nacional, Unidad León",
    job: "Research Nurse",
  },
  {
    id: "01JAC8CXXPJCD99BXQ5YPN0GQK",
    name: "Brynna Kemm",
    university: "South China University of Technology",
    job: "Web Designer II",
  },
  {
    id: "01JAC8CXXQT9WXF5EKK9G6497R",
    name: "Arnaldo Jindrak",
    university: "Langston University",
    job: "VP Accounting",
  },
  {
    id: "01JAC8CXXR37PP4SDD2BG0238P",
    name: "Gwenore Brimacombe",
    university: 'Music Academy "Karol Lipinski" in Wroclaw',
    job: "Nurse Practicioner",
  },
  {
    id: "01JAC8CXXS4N0M7F89ENM1J0X3",
    name: "Bobby Aizkovitch",
    university: "Shanghai Jiaotong University",
    job: "Assistant Manager",
  },
  {
    id: "01JAC8CXXTGYEQ7JY1BH83WXQ1",
    name: "Ag Robbert",
    university:
      "Indian Institute of Information Technology and Management - Kerala",
    job: "GIS Technical Architect",
  },
  {
    id: "01JAC8CXXVC4MSKWWNFRDWVF38",
    name: "Iago Renfield",
    university: "Jodhpur National University",
    job: "Internal Auditor",
  },
  {
    id: "01JAC8CXXWN1WAMKVF9GBVDRVT",
    name: "Cherye Ketteridge",
    university: "Ecole Supérieure d'Informatique-Electronique-Automatique",
    job: "VP Accounting",
  },
];
